// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neuuzliovqwhitwxfndr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldXV6bGlvdnF3aGl0d3hmbmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjkwMzYsImV4cCI6MjA2NTg0NTAzNn0.X6cIcd0hnJGJivApYXbDYftPMQYG7M356OgrIzaUXC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);